"""first sql

Revision ID: 898ac2d9e9df
Revises: 
Create Date: 2024-08-18 20:18:40.546703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '898ac2d9e9df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()   # noqa
    raw_sql = """CREATE OR REPLACE FUNCTION now_ets() RETURNS integer AS $$ 
        select cast(extract(epoch from current_timestamp) as integer) - 3786912000
    $$ LANGUAGE SQL;"""
    conn.execute(sa.text(raw_sql))

    raw_sql = """CREATE OR REPLACE FUNCTION ts2ets(in ts timestamptz) RETURNS integer AS $$ 
        select cast(extract(epoch from ts) as integer) - 3786912000
    $$ LANGUAGE SQL;"""
    conn.execute(sa.text(raw_sql))

    raw_sql = """CREATE OR REPLACE FUNCTION ets2ts(in ts integer) RETURNS timestamptz AS $$ 
        select to_timestamp ((ts + 3786912000)::integer)
    $$ LANGUAGE SQL;"""
    conn.execute(sa.text(raw_sql))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

