"""cate_meta add name

Revision ID: 3f34ba4b6fcb
Revises: ade358b62638
Create Date: 2025-01-16 21:32:35.761939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f34ba4b6fcb'
down_revision = 'ade358b62638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cate_meta', sa.Column('name', sa.String(length=128), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###

    # direct query
    # conn = op.get_bind()   # noqa
    # raw_sql = """   """
    # conn.execute(sa.text(raw_sql))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cate_meta', 'name')
    # ### end Alembic commands ###

    # direct query
    # conn = op.get_bind()   # noqa
    # raw_sql = """   """"
    # conn.execute(sa.text(raw_sql))
