"""base_db

Revision ID: c91b3377cf2e
Revises: f969eae353a9
Create Date: 2025-01-27 19:42:31.104384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91b3377cf2e'
down_revision = 'f969eae353a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('category_meta_id', sa.SmallInteger(), nullable=True))
    op.drop_column('deal', 'category')
    op.add_column('person', sa.Column('nickname', sa.String(length=128), server_default=sa.text("''"), nullable=False))
    op.add_column('person', sa.Column('category_meta_id', sa.SmallInteger(), nullable=True))
    op.drop_column('person', 'category')
    op.drop_column('person', 'name')
    op.add_column('person_grp\t', sa.Column('category_meta_id', sa.SmallInteger(), nullable=True))
    op.drop_column('person_grp\t', 'category')
    op.add_column('product', sa.Column('category_meta_id', sa.SmallInteger(), nullable=True))
    op.drop_column('product', 'category')
    op.add_column('user', sa.Column('category_meta_id', sa.SmallInteger(), nullable=True))
    op.drop_column('user', 'category')
    # ### end Alembic commands ###

    # direct query
    # conn = op.get_bind()   # noqa
    # raw_sql = """   """
    # conn.execute(sa.text(raw_sql))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('category', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_column('user', 'category_meta_id')
    op.add_column('product', sa.Column('category', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_column('product', 'category_meta_id')
    op.add_column('person_grp\t', sa.Column('category', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_column('person_grp\t', 'category_meta_id')
    op.add_column('person', sa.Column('name', sa.VARCHAR(length=128), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('person', sa.Column('category', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_column('person', 'category_meta_id')
    op.drop_column('person', 'nickname')
    op.add_column('deal', sa.Column('category', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_column('deal', 'category_meta_id')
    # ### end Alembic commands ###

    # direct query
    # conn = op.get_bind()   # noqa
    # raw_sql = """   """"
    # conn.execute(sa.text(raw_sql))
